version: "3.7"

services:
    mysql: 
        image: mysql:8.0.25
        container_name: mysql
        networks: 
            - lamp
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: localhost

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.1.1
        container_name: phpmyadmin
        networks:
            - lamp
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
        links: 
            - mysql
        depends_on:
            - mysql

    php74-apache:
        image: "php:7.4-apache"
        container_name: php74-apache
        restart: always
        networks:
            - lamp
        ports:
            - "8000:80"
        volumes:
            - ./php74-apache/html:/var/www/html
        depends_on:
            - mysql
        links:
            - mysql

networks:
    lamp:
